"""drop saved_workflows (remove workflow feature)

Revision ID: 32c5f38964f1
Revises: 6a28d33dbba7
Create Date: 2026-06-16 11:18:07.408488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '32c5f38964f1'
down_revision: Union[str, Sequence[str], None] = '6a28d33dbba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 直接 drop_table 即可:会连带删掉它自己的索引与外键(MySQL 不允许单独 drop FK 支撑索引)。
    op.drop_table('saved_workflows')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_workflows',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='工作流ID(主键)'),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='归属用户ID'),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False, comment='工作流名'),
    sa.Column('steps', mysql.JSON(), nullable=False, comment='有序步骤列表(JSON 字符串数组)'),
    sa.Column('params', mysql.JSON(), nullable=False, comment='步骤参数(JSON)'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间(UTC)'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('saved_workflows_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    comment='自定义工作流表:用户保存的有序 step 列表 + 参数',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='自定义工作流表:用户保存的有序 step 列表 + 参数',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_saved_workflows_owner_id'), 'saved_workflows', ['owner_id'], unique=False)
    # ### end Alembic commands ###
