"""baseline schema

Revision ID: 5d2d1973fc1a
Revises: 
Create Date: 2026-06-12 16:02:55.763057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2d1973fc1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('dhash', sa.String(length=32), nullable=False),
    sa.Column('chash', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('batch', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_batch'), 'assets', ['batch'], unique=False)
    op.create_index(op.f('ix_assets_chash'), 'assets', ['chash'], unique=False)
    op.create_index(op.f('ix_assets_deleted'), 'assets', ['deleted'], unique=False)
    op.create_index(op.f('ix_assets_dhash'), 'assets', ['dhash'], unique=False)
    op.create_index('ix_assets_owner_deleted', 'assets', ['owner_id', 'deleted'], unique=False)
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_table('collection_tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_tasks_owner_id'), 'collection_tasks', ['owner_id'], unique=False)
    op.create_table('export_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=False),
    sa.Column('width_cm', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('fmt', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_templates_owner_id'), 'export_templates', ['owner_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_owner_created', 'jobs', ['owner_id', 'created_at'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('listing_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_templates_owner_id'), 'listing_templates', ['owner_id'], unique=False)
    op.create_table('mockup_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mockup_templates_org_id'), 'mockup_templates', ['org_id'], unique=False)
    op.create_index(op.f('ix_mockup_templates_owner_id'), 'mockup_templates', ['owner_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('print_path', sa.String(length=512), nullable=False),
    sa.Column('mockup_path', sa.String(length=512), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('batch', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_batch'), 'products', ['batch'], unique=False)
    op.create_index(op.f('ix_products_owner_id'), 'products', ['owner_id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_table('saved_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_workflows_owner_id'), 'saved_workflows', ['owner_id'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_owner_id'), 'shops', ['owner_id'], unique=False)
    op.create_table('collected_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('hires_url', sa.String(length=1024), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('price', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('synced', sa.Boolean(), nullable=False),
    sa.Column('synced_asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_url', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['collection_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collected_images_synced'), 'collected_images', ['synced'], unique=False)
    op.create_index(op.f('ix_collected_images_task_id'), 'collected_images', ['task_id'], unique=False)
    op.create_index('ix_collected_task_synced', 'collected_images', ['task_id', 'synced'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_product_id'), 'listings', ['product_id'], unique=False)
    op.create_table('mockup_template_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['mockup_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mockup_template_images_template_id'), 'mockup_template_images', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mockup_template_images_template_id'), table_name='mockup_template_images')
    op.drop_table('mockup_template_images')
    op.drop_index(op.f('ix_listings_product_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index('ix_collected_task_synced', table_name='collected_images')
    op.drop_index(op.f('ix_collected_images_task_id'), table_name='collected_images')
    op.drop_index(op.f('ix_collected_images_synced'), table_name='collected_images')
    op.drop_table('collected_images')
    op.drop_index(op.f('ix_shops_owner_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_saved_workflows_owner_id'), table_name='saved_workflows')
    op.drop_table('saved_workflows')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_owner_id'), table_name='products')
    op.drop_index(op.f('ix_products_batch'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_mockup_templates_owner_id'), table_name='mockup_templates')
    op.drop_index(op.f('ix_mockup_templates_org_id'), table_name='mockup_templates')
    op.drop_table('mockup_templates')
    op.drop_index(op.f('ix_listing_templates_owner_id'), table_name='listing_templates')
    op.drop_table('listing_templates')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_owner_created', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_export_templates_owner_id'), table_name='export_templates')
    op.drop_table('export_templates')
    op.drop_index(op.f('ix_collection_tasks_owner_id'), table_name='collection_tasks')
    op.drop_table('collection_tasks')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_index('ix_assets_owner_deleted', table_name='assets')
    op.drop_index(op.f('ix_assets_dhash'), table_name='assets')
    op.drop_index(op.f('ix_assets_deleted'), table_name='assets')
    op.drop_index(op.f('ix_assets_chash'), table_name='assets')
    op.drop_index(op.f('ix_assets_batch'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
