"""remaining table column comments

Revision ID: 6a28d33dbba7
Revises: a7de78efae2f
Create Date: 2026-06-16 10:43:35.712720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a28d33dbba7'
down_revision: Union[str, Sequence[str], None] = 'a7de78efae2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collected_images', 'id',
               existing_type=mysql.INTEGER(),
               comment='采集图ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('collected_images', 'task_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='所属采集任务ID(FK collection_tasks.id)',
               existing_nullable=False)
    op.alter_column('collected_images', 'url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               comment='原图URL(采集到的图片地址)',
               existing_nullable=False)
    op.alter_column('collected_images', 'hires_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               comment='高清图URL(若有)',
               existing_nullable=False)
    op.alter_column('collected_images', 'platform',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='来源平台:temu/amazon 等',
               existing_nullable=False)
    op.alter_column('collected_images', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='商品标题',
               existing_nullable=False)
    op.alter_column('collected_images', 'selected',
               existing_type=mysql.TINYINT(display_width=1),
               comment='工作台是否勾选',
               existing_nullable=False)
    op.alter_column('collected_images', 'price',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='商品价格(文本)',
               existing_nullable=False)
    op.alter_column('collected_images', 'rating',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='商品评分(文本)',
               existing_nullable=False)
    op.alter_column('collected_images', 'source_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               comment='商品详情页URL',
               existing_nullable=False)
    op.alter_column('collected_images', 'synced',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否已同步入库(true=已取图存为 Asset 进找图库)',
               existing_nullable=False)
    op.alter_column('collected_images', 'synced_asset_id',
               existing_type=mysql.INTEGER(),
               comment='同步后对应的素材ID(Asset.id)',
               existing_nullable=True)
    op.alter_column('collected_images', 'asset_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               comment='同步后素材的对外直链(/files/...)',
               existing_nullable=False)
    op.create_table_comment(
        'collected_images',
        '采集图表:暂存(synced=0)+ 同步入库后的富记录(图+标题/价格/评分/来源链接)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('collection_tasks', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='采集任务ID(随机hex)',
               existing_nullable=False)
    op.alter_column('collection_tasks', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment='归属用户ID',
               existing_nullable=False)
    op.alter_column('collection_tasks', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='采集来源(默认 plugin 浏览器插件)',
               existing_nullable=False)
    op.alter_column('collection_tasks', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='状态:collected已采集等',
               existing_nullable=False)
    op.alter_column('collection_tasks', 'count',
               existing_type=mysql.INTEGER(),
               comment='本次采集图片数',
               existing_nullable=False)
    op.alter_column('collection_tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间(UTC)',
               existing_nullable=False)
    op.create_table_comment(
        'collection_tasks',
        '采集任务表:一次采集动作(聚合若干采集图)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('export_templates', 'id',
               existing_type=mysql.INTEGER(),
               comment='导出模板ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('export_templates', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment='归属用户ID',
               existing_nullable=False)
    op.alter_column('export_templates', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='模板名',
               existing_nullable=False)
    op.alter_column('export_templates', 'dpi',
               existing_type=mysql.INTEGER(),
               comment='分辨率(DPI,默认300)',
               existing_nullable=False)
    op.alter_column('export_templates', 'width_cm',
               existing_type=mysql.FLOAT(),
               comment='画布宽(厘米)',
               existing_nullable=False)
    op.alter_column('export_templates', 'height_cm',
               existing_type=mysql.FLOAT(),
               comment='画布高(厘米)',
               existing_nullable=False)
    op.alter_column('export_templates', 'fmt',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='导出格式:png/jpg/tiff/pdf 等',
               existing_nullable=False)
    op.alter_column('export_templates', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间(UTC)',
               existing_nullable=False)
    op.create_table_comment(
        'export_templates',
        '导出模板表:印花/套图导出规格(分辨率、画布尺寸、格式)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('listing_templates', 'id',
               existing_type=mysql.INTEGER(),
               comment='刊登模板ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('listing_templates', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment='归属用户ID',
               existing_nullable=False)
    op.alter_column('listing_templates', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='模板名',
               existing_nullable=False)
    op.alter_column('listing_templates', 'platform',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='适用平台',
               existing_nullable=False)
    op.alter_column('listing_templates', 'fields',
               existing_type=mysql.JSON(),
               comment='刊登字段(JSON:标题/描述/属性等)',
               existing_nullable=False)
    op.alter_column('listing_templates', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间(UTC)',
               existing_nullable=False)
    op.create_table_comment(
        'listing_templates',
        '刊登模板表:某平台一套可复用的刊登字段(标题/描述/属性)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('mockup_template_images', 'id',
               existing_type=mysql.INTEGER(),
               comment='模板图ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('mockup_template_images', 'template_id',
               existing_type=mysql.INTEGER(),
               comment='所属套图模板ID(FK mockup_templates.id,级联删)',
               existing_nullable=False)
    op.alter_column('mockup_template_images', 'path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               comment='产品照对外url(/files/{作业ID}/{文件名})',
               existing_nullable=False)
    op.alter_column('mockup_template_images', 'idx',
               existing_type=mysql.INTEGER(),
               comment='展示顺序',
               existing_nullable=False)
    op.alter_column('mockup_template_images', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间(UTC)',
               existing_nullable=False)
    op.create_table_comment(
        'mockup_template_images',
        '套图模板图表:某套图模板下的一张产品照',
        existing_comment=None,
        schema=None
    )
    op.alter_column('mockup_templates', 'id',
               existing_type=mysql.INTEGER(),
               comment='套图模板ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('mockup_templates', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment='创建者用户ID',
               existing_nullable=False)
    op.alter_column('mockup_templates', 'org_id',
               existing_type=mysql.INTEGER(),
               comment='团队/组织ID(同组共享,当前统一=1)',
               existing_nullable=False)
    op.alter_column('mockup_templates', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='模板名',
               existing_nullable=False)
    op.alter_column('mockup_templates', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间(UTC)',
               existing_nullable=False)
    op.create_table_comment(
        'mockup_templates',
        '套图模板表:一组产品照(团队资源,按 org 共享),用于商品套图替换印花',
        existing_comment=None,
        schema=None
    )
    op.alter_column('saved_workflows', 'id',
               existing_type=mysql.INTEGER(),
               comment='工作流ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('saved_workflows', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment='归属用户ID',
               existing_nullable=False)
    op.alter_column('saved_workflows', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='工作流名',
               existing_nullable=False)
    op.alter_column('saved_workflows', 'steps',
               existing_type=mysql.JSON(),
               comment='有序步骤列表(JSON 字符串数组)',
               existing_nullable=False)
    op.alter_column('saved_workflows', 'params',
               existing_type=mysql.JSON(),
               comment='步骤参数(JSON)',
               existing_nullable=False)
    op.alter_column('saved_workflows', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间(UTC)',
               existing_nullable=False)
    op.create_table_comment(
        'saved_workflows',
        '自定义工作流表:用户保存的有序 step 列表 + 参数',
        existing_comment=None,
        schema=None
    )
    op.alter_column('shops', 'id',
               existing_type=mysql.INTEGER(),
               comment='店铺ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('shops', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment='归属用户ID',
               existing_nullable=False)
    op.alter_column('shops', 'platform',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='平台:temu / tiktok / etsy / local',
               existing_nullable=False)
    op.alter_column('shops', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='店铺名',
               existing_nullable=False)
    op.alter_column('shops', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='状态:active启用 等',
               existing_nullable=False)
    op.alter_column('shops', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间(UTC)',
               existing_nullable=False)
    op.create_table_comment(
        'shops',
        '店铺表:用户在各平台开的店铺,按店铺上架商品',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'shops',
        existing_comment='店铺表:用户在各平台开的店铺,按店铺上架商品',
        schema=None
    )
    op.alter_column('shops', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间(UTC)',
               existing_nullable=False)
    op.alter_column('shops', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment=None,
               existing_comment='状态:active启用 等',
               existing_nullable=False)
    op.alter_column('shops', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='店铺名',
               existing_nullable=False)
    op.alter_column('shops', 'platform',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='平台:temu / tiktok / etsy / local',
               existing_nullable=False)
    op.alter_column('shops', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='归属用户ID',
               existing_nullable=False)
    op.alter_column('shops', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='店铺ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'saved_workflows',
        existing_comment='自定义工作流表:用户保存的有序 step 列表 + 参数',
        schema=None
    )
    op.alter_column('saved_workflows', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间(UTC)',
               existing_nullable=False)
    op.alter_column('saved_workflows', 'params',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='步骤参数(JSON)',
               existing_nullable=False)
    op.alter_column('saved_workflows', 'steps',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='有序步骤列表(JSON 字符串数组)',
               existing_nullable=False)
    op.alter_column('saved_workflows', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='工作流名',
               existing_nullable=False)
    op.alter_column('saved_workflows', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='归属用户ID',
               existing_nullable=False)
    op.alter_column('saved_workflows', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='工作流ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'mockup_templates',
        existing_comment='套图模板表:一组产品照(团队资源,按 org 共享),用于商品套图替换印花',
        schema=None
    )
    op.alter_column('mockup_templates', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间(UTC)',
               existing_nullable=False)
    op.alter_column('mockup_templates', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='模板名',
               existing_nullable=False)
    op.alter_column('mockup_templates', 'org_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='团队/组织ID(同组共享,当前统一=1)',
               existing_nullable=False)
    op.alter_column('mockup_templates', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='创建者用户ID',
               existing_nullable=False)
    op.alter_column('mockup_templates', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='套图模板ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'mockup_template_images',
        existing_comment='套图模板图表:某套图模板下的一张产品照',
        schema=None
    )
    op.alter_column('mockup_template_images', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间(UTC)',
               existing_nullable=False)
    op.alter_column('mockup_template_images', 'idx',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='展示顺序',
               existing_nullable=False)
    op.alter_column('mockup_template_images', 'path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               comment=None,
               existing_comment='产品照对外url(/files/{作业ID}/{文件名})',
               existing_nullable=False)
    op.alter_column('mockup_template_images', 'template_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属套图模板ID(FK mockup_templates.id,级联删)',
               existing_nullable=False)
    op.alter_column('mockup_template_images', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='模板图ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'listing_templates',
        existing_comment='刊登模板表:某平台一套可复用的刊登字段(标题/描述/属性)',
        schema=None
    )
    op.alter_column('listing_templates', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间(UTC)',
               existing_nullable=False)
    op.alter_column('listing_templates', 'fields',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='刊登字段(JSON:标题/描述/属性等)',
               existing_nullable=False)
    op.alter_column('listing_templates', 'platform',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='适用平台',
               existing_nullable=False)
    op.alter_column('listing_templates', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='模板名',
               existing_nullable=False)
    op.alter_column('listing_templates', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='归属用户ID',
               existing_nullable=False)
    op.alter_column('listing_templates', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='刊登模板ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'export_templates',
        existing_comment='导出模板表:印花/套图导出规格(分辨率、画布尺寸、格式)',
        schema=None
    )
    op.alter_column('export_templates', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间(UTC)',
               existing_nullable=False)
    op.alter_column('export_templates', 'fmt',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment=None,
               existing_comment='导出格式:png/jpg/tiff/pdf 等',
               existing_nullable=False)
    op.alter_column('export_templates', 'height_cm',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='画布高(厘米)',
               existing_nullable=False)
    op.alter_column('export_templates', 'width_cm',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='画布宽(厘米)',
               existing_nullable=False)
    op.alter_column('export_templates', 'dpi',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='分辨率(DPI,默认300)',
               existing_nullable=False)
    op.alter_column('export_templates', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='模板名',
               existing_nullable=False)
    op.alter_column('export_templates', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='归属用户ID',
               existing_nullable=False)
    op.alter_column('export_templates', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='导出模板ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'collection_tasks',
        existing_comment='采集任务表:一次采集动作(聚合若干采集图)',
        schema=None
    )
    op.alter_column('collection_tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间(UTC)',
               existing_nullable=False)
    op.alter_column('collection_tasks', 'count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='本次采集图片数',
               existing_nullable=False)
    op.alter_column('collection_tasks', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment=None,
               existing_comment='状态:collected已采集等',
               existing_nullable=False)
    op.alter_column('collection_tasks', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='采集来源(默认 plugin 浏览器插件)',
               existing_nullable=False)
    op.alter_column('collection_tasks', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='归属用户ID',
               existing_nullable=False)
    op.alter_column('collection_tasks', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='采集任务ID(随机hex)',
               existing_nullable=False)
    op.drop_table_comment(
        'collected_images',
        existing_comment='采集图表:暂存(synced=0)+ 同步入库后的富记录(图+标题/价格/评分/来源链接)',
        schema=None
    )
    op.alter_column('collected_images', 'asset_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               comment=None,
               existing_comment='同步后素材的对外直链(/files/...)',
               existing_nullable=False)
    op.alter_column('collected_images', 'synced_asset_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='同步后对应的素材ID(Asset.id)',
               existing_nullable=True)
    op.alter_column('collected_images', 'synced',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否已同步入库(true=已取图存为 Asset 进找图库)',
               existing_nullable=False)
    op.alter_column('collected_images', 'source_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               comment=None,
               existing_comment='商品详情页URL',
               existing_nullable=False)
    op.alter_column('collected_images', 'rating',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment=None,
               existing_comment='商品评分(文本)',
               existing_nullable=False)
    op.alter_column('collected_images', 'price',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='商品价格(文本)',
               existing_nullable=False)
    op.alter_column('collected_images', 'selected',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='工作台是否勾选',
               existing_nullable=False)
    op.alter_column('collected_images', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='商品标题',
               existing_nullable=False)
    op.alter_column('collected_images', 'platform',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='来源平台:temu/amazon 等',
               existing_nullable=False)
    op.alter_column('collected_images', 'hires_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               comment=None,
               existing_comment='高清图URL(若有)',
               existing_nullable=False)
    op.alter_column('collected_images', 'url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               comment=None,
               existing_comment='原图URL(采集到的图片地址)',
               existing_nullable=False)
    op.alter_column('collected_images', 'task_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='所属采集任务ID(FK collection_tasks.id)',
               existing_nullable=False)
    op.alter_column('collected_images', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='采集图ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
