"""asset owner_created index + core table column comments

Revision ID: a7de78efae2f
Revises: 5d2d1973fc1a
Create Date: 2026-06-16 10:22:18.758906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a7de78efae2f'
down_revision: Union[str, Sequence[str], None] = '5d2d1973fc1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'id',
               existing_type=mysql.INTEGER(),
               comment='素材ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('assets', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment='归属用户ID(谁的)',
               existing_nullable=False)
    op.alter_column('assets', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='素材名称(展示用,如『图生视频 通用』)',
               existing_nullable=False)
    op.alter_column('assets', 'path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               comment='文件位置 /files/{作业ID}/{文件名};对应对象存储 images/ 或 videos/ 下的对象',
               existing_nullable=False)
    op.alter_column('assets', 'dhash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='感知哈希-结构(亮度梯度),查重/侵权用',
               existing_nullable=False)
    op.alter_column('assets', 'chash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment='感知哈希-颜色签名(4x4 RGB)',
               existing_nullable=False)
    op.alter_column('assets', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='来源:upload上传 / collected采集 / generated生成',
               existing_nullable=False)
    op.alter_column('assets', 'risk',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='侵权风险:safe安全 / review待复核 / high高危 / unknown未知',
               existing_nullable=False)
    op.alter_column('assets', 'deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否在回收站(软删,true=已移入回收站)',
               existing_nullable=False)
    op.alter_column('assets', 'batch',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='批次标识(批量操作分组)',
               existing_nullable=False)
    op.alter_column('assets', 'tags',
               existing_type=mysql.JSON(),
               comment='标签(JSON 字符串数组)',
               existing_nullable=False)
    op.alter_column('assets', 'size_bytes',
               existing_type=mysql.INTEGER(),
               comment='文件大小(字节);存储配额按此列加总',
               existing_nullable=False)
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间(UTC),时间筛选/排序依据',
               existing_nullable=False)
    op.create_index('ix_assets_owner_created', 'assets', ['owner_id', 'created_at'], unique=False)
    op.create_table_comment(
        'assets',
        '素材表:每个上传/生成的图片·视频·文件一行;我的空间、存储配额、回收站的数据源',
        existing_comment=None,
        schema=None
    )
    op.alter_column('jobs', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='作业ID(随机12位hex,同时作为产物目录 outputs/{id} 与对象 key 的一段)',
               existing_nullable=False)
    op.alter_column('jobs', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment='归属用户ID(可空=系统作业)',
               existing_nullable=True)
    op.alter_column('jobs', 'kind',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='作业类型:process抠图/generate文生图/edit改图/aivideo图生视频 等',
               existing_nullable=False)
    op.alter_column('jobs', 'tool_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='前端工具ID(tools.js);用于我的空间按工具分组展示',
               existing_nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='状态:pending排队 / running执行中 / done完成 / error失败',
               existing_nullable=False)
    op.alter_column('jobs', 'params',
               existing_type=mysql.JSON(),
               comment='作业入参(JSON)',
               existing_nullable=False)
    op.alter_column('jobs', 'result',
               existing_type=mysql.JSON(),
               comment='作业结果(JSON,含产物 *_url)',
               existing_nullable=False)
    op.alter_column('jobs', 'error',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='失败信息(异常类型+消息)',
               existing_nullable=False)
    op.alter_column('jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建(入队)时间(UTC)',
               existing_nullable=False)
    op.alter_column('jobs', 'started_at',
               existing_type=mysql.DATETIME(),
               comment='开始执行时间(UTC)',
               existing_nullable=True)
    op.alter_column('jobs', 'finished_at',
               existing_type=mysql.DATETIME(),
               comment='结束时间(done/error,UTC)',
               existing_nullable=True)
    op.create_table_comment(
        'jobs',
        '异步作业表:状态/结果的唯一真相源,前端轮询 /api/jobs/{id};作业ID 也是产物文件夹名',
        existing_comment=None,
        schema=None
    )
    op.alter_column('listings', 'id',
               existing_type=mysql.INTEGER(),
               comment='上架记录ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('listings', 'product_id',
               existing_type=mysql.INTEGER(),
               comment='商品ID(FK products.id)',
               existing_nullable=False)
    op.alter_column('listings', 'platform',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='平台:temu / tiktok / etsy / local',
               existing_nullable=False)
    op.alter_column('listings', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='上架状态:draft草稿 / published已上架 / failed失败',
               existing_nullable=False)
    op.alter_column('listings', 'external_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment='平台侧商品ID(上架成功后回填)',
               existing_nullable=False)
    op.alter_column('listings', 'payload',
               existing_type=mysql.JSON(),
               comment='上架请求/回执载荷(JSON)',
               existing_nullable=False)
    op.alter_column('listings', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间(UTC)',
               existing_nullable=False)
    op.create_table_comment(
        'listings',
        '上架记录表:某商品在某平台(temu/tiktok/etsy…)的上架状态',
        existing_comment=None,
        schema=None
    )
    op.alter_column('products', 'id',
               existing_type=mysql.INTEGER(),
               comment='商品ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment='归属用户ID',
               existing_nullable=False)
    op.alter_column('products', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='商品标题',
               existing_nullable=False)
    op.alter_column('products', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='品类(默认 apparel 服装)',
               existing_nullable=False)
    op.alter_column('products', 'price',
               existing_type=mysql.FLOAT(),
               comment='售价',
               existing_nullable=False)
    op.alter_column('products', 'print_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               comment='印花文件位置(/files/...)',
               existing_nullable=False)
    op.alter_column('products', 'mockup_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               comment='套图预览文件位置(/files/...)',
               existing_nullable=False)
    op.alter_column('products', 'attrs',
               existing_type=mysql.JSON(),
               comment='扩展属性(JSON,颜色/尺码等)',
               existing_nullable=False)
    op.alter_column('products', 'sku',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='SKU 货号',
               existing_nullable=False)
    op.alter_column('products', 'batch',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='批次标识',
               existing_nullable=False)
    op.alter_column('products', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='来源:manual手建 / 其它',
               existing_nullable=False)
    op.alter_column('products', 'risk',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='侵权风险:safe/review/high/unknown',
               existing_nullable=False)
    op.alter_column('products', 'tags',
               existing_type=mysql.JSON(),
               comment='标签(JSON 数组)',
               existing_nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间(UTC)',
               existing_nullable=False)
    op.create_table_comment(
        'products',
        '商品库表:可上架的商品条目(印花+套图+属性)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(),
               comment='用户ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='登录邮箱(唯一)',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='密码哈希(pbkdf2,不存明文)',
               existing_nullable=False)
    op.alter_column('users', 'credits',
               existing_type=mysql.INTEGER(),
               comment='计费点数余额(作图按操作扣点)',
               existing_nullable=False)
    op.alter_column('users', 'org_id',
               existing_type=mysql.INTEGER(),
               comment='团队/组织ID(团队资源共享维度,当前统一=1)',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='注册时间(UTC)',
               existing_nullable=False)
    op.create_table_comment(
        'users',
        '用户表:账号、密码、计费点数、团队归属',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='用户表:账号、密码、计费点数、团队归属',
        schema=None
    )
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='注册时间(UTC)',
               existing_nullable=False)
    op.alter_column('users', 'org_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='团队/组织ID(团队资源共享维度,当前统一=1)',
               existing_nullable=False)
    op.alter_column('users', 'credits',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='计费点数余额(作图按操作扣点)',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='密码哈希(pbkdf2,不存明文)',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='登录邮箱(唯一)',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'products',
        existing_comment='商品库表:可上架的商品条目(印花+套图+属性)',
        schema=None
    )
    op.alter_column('products', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间(UTC)',
               existing_nullable=False)
    op.alter_column('products', 'tags',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='标签(JSON 数组)',
               existing_nullable=False)
    op.alter_column('products', 'risk',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment=None,
               existing_comment='侵权风险:safe/review/high/unknown',
               existing_nullable=False)
    op.alter_column('products', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='来源:manual手建 / 其它',
               existing_nullable=False)
    op.alter_column('products', 'batch',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='批次标识',
               existing_nullable=False)
    op.alter_column('products', 'sku',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='SKU 货号',
               existing_nullable=False)
    op.alter_column('products', 'attrs',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='扩展属性(JSON,颜色/尺码等)',
               existing_nullable=False)
    op.alter_column('products', 'mockup_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               comment=None,
               existing_comment='套图预览文件位置(/files/...)',
               existing_nullable=False)
    op.alter_column('products', 'print_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               comment=None,
               existing_comment='印花文件位置(/files/...)',
               existing_nullable=False)
    op.alter_column('products', 'price',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='售价',
               existing_nullable=False)
    op.alter_column('products', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='品类(默认 apparel 服装)',
               existing_nullable=False)
    op.alter_column('products', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='商品标题',
               existing_nullable=False)
    op.alter_column('products', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='归属用户ID',
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='商品ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'listings',
        existing_comment='上架记录表:某商品在某平台(temu/tiktok/etsy…)的上架状态',
        schema=None
    )
    op.alter_column('listings', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间(UTC)',
               existing_nullable=False)
    op.alter_column('listings', 'payload',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='上架请求/回执载荷(JSON)',
               existing_nullable=False)
    op.alter_column('listings', 'external_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment=None,
               existing_comment='平台侧商品ID(上架成功后回填)',
               existing_nullable=False)
    op.alter_column('listings', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment=None,
               existing_comment='上架状态:draft草稿 / published已上架 / failed失败',
               existing_nullable=False)
    op.alter_column('listings', 'platform',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='平台:temu / tiktok / etsy / local',
               existing_nullable=False)
    op.alter_column('listings', 'product_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='商品ID(FK products.id)',
               existing_nullable=False)
    op.alter_column('listings', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='上架记录ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'jobs',
        existing_comment='异步作业表:状态/结果的唯一真相源,前端轮询 /api/jobs/{id};作业ID 也是产物文件夹名',
        schema=None
    )
    op.alter_column('jobs', 'finished_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='结束时间(done/error,UTC)',
               existing_nullable=True)
    op.alter_column('jobs', 'started_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='开始执行时间(UTC)',
               existing_nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建(入队)时间(UTC)',
               existing_nullable=False)
    op.alter_column('jobs', 'error',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='失败信息(异常类型+消息)',
               existing_nullable=False)
    op.alter_column('jobs', 'result',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='作业结果(JSON,含产物 *_url)',
               existing_nullable=False)
    op.alter_column('jobs', 'params',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='作业入参(JSON)',
               existing_nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment=None,
               existing_comment='状态:pending排队 / running执行中 / done完成 / error失败',
               existing_nullable=False)
    op.alter_column('jobs', 'tool_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='前端工具ID(tools.js);用于我的空间按工具分组展示',
               existing_nullable=False)
    op.alter_column('jobs', 'kind',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='作业类型:process抠图/generate文生图/edit改图/aivideo图生视频 等',
               existing_nullable=False)
    op.alter_column('jobs', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='归属用户ID(可空=系统作业)',
               existing_nullable=True)
    op.alter_column('jobs', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='作业ID(随机12位hex,同时作为产物目录 outputs/{id} 与对象 key 的一段)',
               existing_nullable=False)
    op.drop_table_comment(
        'assets',
        existing_comment='素材表:每个上传/生成的图片·视频·文件一行;我的空间、存储配额、回收站的数据源',
        schema=None
    )
    op.drop_index('ix_assets_owner_created', table_name='assets')
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间(UTC),时间筛选/排序依据',
               existing_nullable=False)
    op.alter_column('assets', 'size_bytes',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='文件大小(字节);存储配额按此列加总',
               existing_nullable=False)
    op.alter_column('assets', 'tags',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='标签(JSON 字符串数组)',
               existing_nullable=False)
    op.alter_column('assets', 'batch',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='批次标识(批量操作分组)',
               existing_nullable=False)
    op.alter_column('assets', 'deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否在回收站(软删,true=已移入回收站)',
               existing_nullable=False)
    op.alter_column('assets', 'risk',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment=None,
               existing_comment='侵权风险:safe安全 / review待复核 / high高危 / unknown未知',
               existing_nullable=False)
    op.alter_column('assets', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='来源:upload上传 / collected采集 / generated生成',
               existing_nullable=False)
    op.alter_column('assets', 'chash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment=None,
               existing_comment='感知哈希-颜色签名(4x4 RGB)',
               existing_nullable=False)
    op.alter_column('assets', 'dhash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='感知哈希-结构(亮度梯度),查重/侵权用',
               existing_nullable=False)
    op.alter_column('assets', 'path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               comment=None,
               existing_comment='文件位置 /files/{作业ID}/{文件名};对应对象存储 images/ 或 videos/ 下的对象',
               existing_nullable=False)
    op.alter_column('assets', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='素材名称(展示用,如『图生视频 通用』)',
               existing_nullable=False)
    op.alter_column('assets', 'owner_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='归属用户ID(谁的)',
               existing_nullable=False)
    op.alter_column('assets', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='素材ID(主键)',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
